### ISSUE TITLE
Cannot find module 'graphql-tag'

### ISSUE THREAD

**Issue by raphaelns-developer** [bgentry/ember-apollo-client#176]
After installing the addon and running ember server I get the following error:
```js
Cannot find module 'graphql-tag'
Error: Cannot find module 'graphql-tag'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/willrax/Code/phoenix/node_modules/ember-apollo-client/lib/graphql-filter.js:4:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```
I'm running the following:

ember-cli: 3.5.0
node: 8.9.4
os: linux x64

**Comment by jasonmit** [comment]
@raphaelns-developer as of 2.x we no longer bundle graphql-tag as it's not used internally.  If you need the dependency, add ember-cli-auto-import to your app if it already isn't and add graphql-tag as a dependency.  After that, you should be set.
